app <- ShinyLoadDriver$new()
app$snapshotInit("myloadtest")

Sys.sleep(3.0)
app$setInputs(beta = 1.75, values_ = FALSE, wait_ = FALSE)
Sys.sleep(0.3)
app$setInputs(beta = 2, timeout_ = 3000)
Sys.sleep(2.8)
app$setInputs(beta = 1.25, timeout_ = 3000)
Sys.sleep(0.1)
app$setInputs(beta = 1, timeout_ = 3000)
Sys.sleep(3.3)
app$setInputs(gamma = 4, timeout_ = 3000)
Sys.sleep(2.5)
app$setInputs(gamma = 3, timeout_ = 3000)
Sys.sleep(0.0)
app$setInputs(gamma = 2, timeout_ = 3000)
Sys.sleep(2.1)
app$setInputs(beta = 1.25, timeout_ = 3000)
Sys.sleep(2.4)
app$setInputs(reset = "click", values_ = FALSE, wait_ = FALSE)
Sys.sleep(0.1)
app$setInputs(beta = 1.5, values_ = FALSE, wait_ = FALSE)
Sys.sleep(0.0)
app$setInputs(gamma = 7, timeout_ = 3000)

app$snapshot()
app$stop()
app$getEventLog()
